### ISSUE TITLE
Hi! We've got the same idea!

### ISSUE THREAD

**Issue by s011110101** [abnormalitydancingirl/abnormalcopylock#1]
I got the same issue with you! I've made a AppleScript [here](https://github.com/s011110101/cmu-online-academy-paster). Please feel free to use it if you are using MacOS! 😆

**Comment by abnormalitydancingirl** [comment]
i use windows but never uploaded the file here. found a workaround months ago... thanks for this though

**Comment by s011110101** [comment]
Cool! It's always happy to break the rules ;)
